import "./globals.css";
import Layout from '@/layout/layout';
import { ReactNode } from 'react';

// تعریف تایپ برای پراپرتی‌های کامپوننت RootLayout
interface RootLayoutProps {
  children: ReactNode;
  isLoading?: boolean; // اضافه کردن پراپرتی isLoading
}

export const metadata = {
  title: 'mahbano',
  description: 'Generated by create next app',
  icons: {
    icon: ['/images/652bd6145dc61.webp'],
    apple: ['/'],
    shortcut: ['/']
  }
};

export default function RootLayout({ children, isLoading = false }: RootLayoutProps) {
  return (
    <html lang="fa" dir='rtl'>
      <body>
        <Layout isLoading={isLoading}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
