import "./globals.css";
import Layout from '@/layout/Layout';


export const metadata = {
  title: 'mahbano',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
      <body >
        <Layout >
          {children}
        </Layout>
      </body>
    </html>
  )
}
